apiVersion: aws.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: network-team
spec:
  credentials:
    secretRef:
      key: credentials
      name: aws-creds
      namespace: network-team
    source: Secret
